# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(548, 347)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 581, 381))
        self.tabWidget.setMinimumSize(QSize(581, 381))
        self.tabWidget.setMaximumSize(QSize(16777215, 381))
        self.tabWidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.btn_ir_worldclock = QPushButton(self.tab)
        self.btn_ir_worldclock.setObjectName(u"btn_ir_worldclock")
        self.btn_ir_worldclock.setGeometry(QRect(90, 190, 121, 31))
        font = QFont()
        font.setFamilies([u"MRT_Nil 3"])
        font.setPointSize(13)
        self.btn_ir_worldclock.setFont(font)
        self.btn_de_worldclock = QPushButton(self.tab)
        self.btn_de_worldclock.setObjectName(u"btn_de_worldclock")
        self.btn_de_worldclock.setGeometry(QRect(240, 190, 121, 31))
        self.btn_de_worldclock.setFont(font)
        self.btn_us_worldclock = QPushButton(self.tab)
        self.btn_us_worldclock.setObjectName(u"btn_us_worldclock")
        self.btn_us_worldclock.setGeometry(QRect(380, 190, 121, 31))
        self.btn_us_worldclock.setFont(font)
        self.label_worldclock = QLabel(self.tab)
        self.label_worldclock.setObjectName(u"label_worldclock")
        self.label_worldclock.setGeometry(QRect(160, 40, 311, 91))
        font1 = QFont()
        font1.setFamilies([u"Seven Segment"])
        font1.setPointSize(52)
        self.label_worldclock.setFont(font1)
        self.label_worldclock.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 521, 341))
        self.tabWidget_2.setMinimumSize(QSize(0, 341))
        self.tabWidget_2.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget_2.setLocale(QLocale(QLocale.English, QLocale.UnitedArabEmirates))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.layoutWidget_2 = QWidget(self.tab_5)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(0, 0, 361, 231))
        self.gl_tasks = QGridLayout(self.layoutWidget_2)
        self.gl_tasks.setObjectName(u"gl_tasks")
        self.gl_tasks.setContentsMargins(0, 0, 0, 0)
        self.le_edet_time = QLineEdit(self.tab_5)
        self.le_edet_time.setObjectName(u"le_edet_time")
        self.le_edet_time.setGeometry(QRect(370, 50, 151, 16))
        self.le_edet_time.setAlignment(Qt.AlignCenter)
        self.le_edet_time.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.le_edet_name = QLineEdit(self.tab_5)
        self.le_edet_name.setObjectName(u"le_edet_name")
        self.le_edet_name.setGeometry(QRect(370, 80, 151, 21))
        self.le_edet_name.setAlignment(Qt.AlignCenter)
        self.le_edet_name.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.label = QLabel(self.tab_5)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(370, 0, 58, 19))
        self.le_edet_id = QLineEdit(self.tab_5)
        self.le_edet_id.setObjectName(u"le_edet_id")
        self.le_edet_id.setGeometry(QRect(370, 20, 151, 16))
        self.le_edet_id.setAlignment(Qt.AlignCenter)
        self.le_edet_id.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.btn_alarm_set_2 = QPushButton(self.tab_5)
        self.btn_alarm_set_2.setObjectName(u"btn_alarm_set_2")
        self.btn_alarm_set_2.setGeometry(QRect(420, 120, 60, 60))
        self.btn_alarm_set_2.setMinimumSize(QSize(60, 60))
        self.btn_alarm_set_2.setMaximumSize(QSize(60, 60))
        font2 = QFont()
        font2.setPointSize(10)
        self.btn_alarm_set_2.setFont(font2)
        self.btn_alarm_set_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_alarm_set_2.setStyleSheet(u"border: 0px; border-radius: 30px; background-color: #000; color: #fff;")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.le_name_alarm = QLineEdit(self.tab_6)
        self.le_name_alarm.setObjectName(u"le_name_alarm")
        self.le_name_alarm.setGeometry(QRect(80, 160, 231, 41))
        self.le_name_alarm.setAlignment(Qt.AlignCenter)
        self.le_name_alarm.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.layoutWidget = QWidget(self.tab_6)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(-20, 0, 481, 140))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(60, 40, 60, 30)
        self.le_tim_alarm = QLineEdit(self.layoutWidget)
        self.le_tim_alarm.setObjectName(u"le_tim_alarm")
        self.le_tim_alarm.setAlignment(Qt.AlignCenter)
        self.le_tim_alarm.setCursorMoveStyle(Qt.LogicalMoveStyle)

        self.horizontalLayout_2.addWidget(self.le_tim_alarm)

        self.btn_alarm_set = QPushButton(self.tab_6)
        self.btn_alarm_set.setObjectName(u"btn_alarm_set")
        self.btn_alarm_set.setGeometry(QRect(340, 150, 60, 60))
        self.btn_alarm_set.setMinimumSize(QSize(60, 60))
        self.btn_alarm_set.setMaximumSize(QSize(60, 60))
        self.btn_alarm_set.setFont(font2)
        self.btn_alarm_set.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_alarm_set.setStyleSheet(u"border: 0px; border-radius: 30px; background-color: #000; color: #fff;")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.btn_start_Stop = QPushButton(self.tab_3)
        self.btn_start_Stop.setObjectName(u"btn_start_Stop")
        self.btn_start_Stop.setGeometry(QRect(100, 150, 80, 27))
        self.btn_stop_Stop = QPushButton(self.tab_3)
        self.btn_stop_Stop.setObjectName(u"btn_stop_Stop")
        self.btn_stop_Stop.setGeometry(QRect(190, 150, 80, 27))
        self.btn_rest_stopw = QPushButton(self.tab_3)
        self.btn_rest_stopw.setObjectName(u"btn_rest_stopw")
        self.btn_rest_stopw.setGeometry(QRect(280, 150, 80, 27))
        self.lbl_stopwatch = QLabel(self.tab_3)
        self.lbl_stopwatch.setObjectName(u"lbl_stopwatch")
        self.lbl_stopwatch.setGeometry(QRect(20, 20, 401, 120))
        self.lbl_stopwatch.setMinimumSize(QSize(0, 120))
        font3 = QFont()
        font3.setFamilies([u"Seven Segment"])
        font3.setPointSize(55)
        self.lbl_stopwatch.setFont(font3)
        self.lbl_stopwatch.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.btn_timer_stop_2 = QPushButton(self.tab_4)
        self.btn_timer_stop_2.setObjectName(u"btn_timer_stop_2")
        self.btn_timer_stop_2.setGeometry(QRect(130, 180, 191, 27))
        self.label_2 = QLabel(self.tab_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 50, 20, 42))
        self.label_2.setMaximumSize(QSize(20, 16777215))
        font4 = QFont()
        font4.setFamilies([u"Seven Segment"])
        font4.setPointSize(30)
        font4.setBold(True)
        self.label_2.setFont(font4)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.btn_timer_start = QPushButton(self.tab_4)
        self.btn_timer_start.setObjectName(u"btn_timer_start")
        self.btn_timer_start.setGeometry(QRect(100, 130, 241, 27))
        self.btn_timer_pause = QPushButton(self.tab_4)
        self.btn_timer_pause.setObjectName(u"btn_timer_pause")
        self.btn_timer_pause.setGeometry(QRect(160, 210, 131, 27))
        self.tb_s = QLineEdit(self.tab_4)
        self.tb_s.setObjectName(u"tb_s")
        self.tb_s.setGeometry(QRect(279, 20, 70, 70))
        self.tb_s.setMinimumSize(QSize(70, 70))
        self.tb_s.setMaximumSize(QSize(70, 70))
        font5 = QFont()
        font5.setFamilies([u"Seven Segment"])
        font5.setPointSize(40)
        self.tb_s.setFont(font5)
        self.tb_s.setAlignment(Qt.AlignCenter)
        self.lineEdit_3 = QLineEdit(self.tab_4)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(256, 20, 15, 70))
        self.lineEdit_3.setMinimumSize(QSize(15, 70))
        self.lineEdit_3.setMaximumSize(QSize(15, 70))
        self.lineEdit_3.setFont(font5)
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.tb_m = QLineEdit(self.tab_4)
        self.tb_m.setObjectName(u"tb_m")
        self.tb_m.setGeometry(QRect(179, 20, 70, 70))
        self.tb_m.setMinimumSize(QSize(70, 70))
        self.tb_m.setMaximumSize(QSize(70, 70))
        self.tb_m.setFont(font5)
        self.tb_m.setAlignment(Qt.AlignCenter)
        self.lineEdit_2 = QLineEdit(self.tab_4)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(157, 20, 15, 70))
        self.lineEdit_2.setMinimumSize(QSize(15, 70))
        self.lineEdit_2.setMaximumSize(QSize(15, 70))
        self.lineEdit_2.setFont(font5)
        self.lineEdit_2.setAlignment(Qt.AlignCenter)
        self.tb_h = QLineEdit(self.tab_4)
        self.tb_h.setObjectName(u"tb_h")
        self.tb_h.setGeometry(QRect(80, 20, 70, 70))
        self.tb_h.setMinimumSize(QSize(70, 70))
        self.tb_h.setMaximumSize(QSize(70, 70))
        self.tb_h.setFont(font5)
        self.tb_h.setAlignment(Qt.AlignCenter)
        self.tb_h_2 = QLineEdit(self.tab_4)
        self.tb_h_2.setObjectName(u"tb_h_2")
        self.tb_h_2.setGeometry(QRect(80, 20, 70, 70))
        self.tb_h_2.setMinimumSize(QSize(70, 70))
        self.tb_h_2.setMaximumSize(QSize(70, 70))
        self.tb_h_2.setFont(font5)
        self.tb_h_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_4 = QLineEdit(self.tab_4)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(157, 20, 15, 70))
        self.lineEdit_4.setMinimumSize(QSize(15, 70))
        self.lineEdit_4.setMaximumSize(QSize(15, 70))
        self.lineEdit_4.setFont(font5)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.lineEdit_5 = QLineEdit(self.tab_4)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(256, 20, 15, 70))
        self.lineEdit_5.setMinimumSize(QSize(15, 70))
        self.lineEdit_5.setMaximumSize(QSize(15, 70))
        self.lineEdit_5.setFont(font5)
        self.lineEdit_5.setAlignment(Qt.AlignCenter)
        self.tb_m_2 = QLineEdit(self.tab_4)
        self.tb_m_2.setObjectName(u"tb_m_2")
        self.tb_m_2.setGeometry(QRect(179, 20, 70, 70))
        self.tb_m_2.setMinimumSize(QSize(70, 70))
        self.tb_m_2.setMaximumSize(QSize(70, 70))
        self.tb_m_2.setFont(font5)
        self.tb_m_2.setAlignment(Qt.AlignCenter)
        self.tb_s_2 = QLineEdit(self.tab_4)
        self.tb_s_2.setObjectName(u"tb_s_2")
        self.tb_s_2.setGeometry(QRect(279, 20, 70, 70))
        self.tb_s_2.setMinimumSize(QSize(70, 70))
        self.tb_s_2.setMaximumSize(QSize(70, 70))
        self.tb_s_2.setFont(font5)
        self.tb_s_2.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 548, 25))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_ir_worldclock.setText(QCoreApplication.translate("MainWindow", u"Iran", None))
        self.btn_de_worldclock.setText(QCoreApplication.translate("MainWindow", u"USA", None))
        self.btn_us_worldclock.setText(QCoreApplication.translate("MainWindow", u"Germany", None))
        self.label_worldclock.setText(QCoreApplication.translate("MainWindow", u"0:0:0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Word Clock", None))
#if QT_CONFIG(tooltip)
        self.le_edet_time.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.le_edet_time.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.le_edet_time.setPlaceholderText(QCoreApplication.translate("MainWindow", u"time", None))
#if QT_CONFIG(tooltip)
        self.le_edet_name.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.le_edet_name.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.le_edet_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"name", None))
        self.label.setText("")
#if QT_CONFIG(tooltip)
        self.le_edet_id.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.le_edet_id.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.le_edet_id.setPlaceholderText(QCoreApplication.translate("MainWindow", u"id", None))
        self.btn_alarm_set_2.setText(QCoreApplication.translate("MainWindow", u"Edet", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Alarms", None))
#if QT_CONFIG(tooltip)
        self.le_name_alarm.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.le_name_alarm.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.le_name_alarm.setPlaceholderText(QCoreApplication.translate("MainWindow", u"name", None))
#if QT_CONFIG(tooltip)
        self.le_tim_alarm.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.le_tim_alarm.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.le_tim_alarm.setPlaceholderText(QCoreApplication.translate("MainWindow", u"tim", None))
        self.btn_alarm_set.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Add Alarm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.btn_start_Stop.setText(QCoreApplication.translate("MainWindow", u"start", None))
        self.btn_stop_Stop.setText(QCoreApplication.translate("MainWindow", u"stop", None))
        self.btn_rest_stopw.setText(QCoreApplication.translate("MainWindow", u"Rest", None))
        self.lbl_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0:0:0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"StopWatch", None))
        self.btn_timer_stop_2.setText(QCoreApplication.translate("MainWindow", u"stop", None))
        self.label_2.setText("")
        self.btn_timer_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_timer_pause.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Timer", None))
    # retranslateUi

